### ISSUE TITLE
1.16 Command Addition

### ISSUE THREAD

**Issue by SmallPepperZ** [Czaplicki/mcfunction-support-resources#5]
A few new commands were added in 1.16, 
`/attribute`, `/locatebiome`, `/gamerule forgiveDeadPlayers` and `/gamerule universalAnger`
https://minecraft.gamepedia.com/Java_Edition_1.16#Command_format
If you're still working on this, it would be great if you could add those

**Comment by czaplicki** [comment]
Sorry, i'm very much not, so feel free to fork.
